version: '3.8'

services:
  mammoth-parser:
    build: .
    container_name: mammoth-docx-parser
    ports:
      - "3330:3330"
    environment:
      - NODE_ENV=production
      - PORT=3330
    volumes:
      # Opcional: montar logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - mammoth-network

networks:
  mammoth-network:
    driver: bridge